<?php

/**
 * Hero Overlap Block Template
 * Generated by Copilot
 */

// Support custom "anchor" values.
$anchor = '';
if (! empty($block['anchor'])) {
  $anchor = $block['anchor'];
}

// Create class attribute allowing for custom "className" and "align" values.
$class_name = 'hero-overlap';
if (! empty($block['className'])) {
  $class_name .= ' ' . $block['className'];
}

// Get fields.
$image = get_field('hero_overlap_image');
$mobile_image = get_field('hero_overlap_mobile_image');
$video = get_field('hero_overlap_video');
$title = get_field('hero_overlap_title');
$subtitle = get_field('hero_overlap_subtitle');
$cta = get_field('hero_overlap_cta');
?>

<section <?php
          if (! empty($anchor)) :
          ?>
  id="<?php echo esc_attr($anchor); ?>" <?php endif; ?> class="<?php echo esc_attr($class_name); ?>">
  <div class="relative w-full">
    <div class="hero-item relative">
      <?php if (! empty($video)): ?>
        <video
          class="w-full h-auto"
          autoplay
          loop
          muted
          fetchpriority="high">
          <source src="<?php echo esc_url($video['url']); ?>" type="video/mp4">
        </video>
      <?php else: ?>
        <?php if (! empty($mobile_image)): ?>
          <img
            class="w-full h-auto block lg:hidden"
            src="<?php echo esc_url($mobile_image['url']); ?>"
            alt="<?php echo esc_attr($mobile_image['alt']); ?>"
            fetchpriority="high" />
        <?php endif; ?>
        <img
          class="w-full h-auto <?php echo empty($mobile_image) ? 'block' : 'hidden lg:block'; ?>"
          src="<?php echo esc_url($image['url']); ?>"
          alt="<?php echo esc_attr($image['alt']); ?>"
          fetchpriority="high" />
      <?php endif; ?>

      <div class="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-black/60 to-transparent gap-4 p-6 lg:p-12">
        <?php if (! empty($title)): ?>
          <h1 class="text-white text-3xl lg:text-5xl font-bold">
            <?php echo esc_html($title); ?>
          </h1>
        <?php endif; ?>

        <?php if (! empty($subtitle)): ?>
          <div class="text-white text-lg lg:text-xl">
            <?php echo wp_kses_post($subtitle); ?>
          </div>
        <?php endif; ?>

        <?php if (! empty($cta)): ?>
          <a
            href="<?php echo esc_url($cta['url']); ?>"
            class="self-start bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
            <?php echo esc_html($cta['title']); ?>
          </a>
        <?php endif; ?>
      </div>
    </div>
  </div>
</section>