<?php
/**
 * Hero Overlap Block Template
 * Generated by Copilot
 */

// Support custom "anchor" values.
$anchor = '';
if ( ! empty($block['anchor']) ) {
    $anchor = esc_attr($block['anchor']);
}

// Create class attribute allowing for custom "className" and "align" values.
$class_name = 'hero-overlap';
if ( ! empty($block['className']) ) {
    $class_name .= ' ' . esc_attr($block['className']);
}

// Get repeater fields.
$items = get_field('hero_overlap_items');
if ( empty($items) ) {
    return; // Exit if no items are provided.
}
?>

<section id="<?php echo $anchor; ?>" class="<?php echo $class_name; ?>">
    <div class="relative w-full">
        <?php foreach ( $items as $item ): ?>
            <?php
            $image = $item['image'];
            $mobile_image = $item['mobile_image'];
            $video = $item['video'];
            $title = $item['title'];
            $subtitle = $item['subtitle'];
            $cta = $item['cta'];
            ?>
            <div class="hero-item relative">
                <?php if ( ! empty( $video ) ): ?>
                    <video
                        class="w-full h-auto"
                        autoplay
                        loop
                        muted
                        poster="<?php echo esc_url( $image['url'] ); ?>"
                        fetchpriority="high"
                    >
                        <source src="<?php echo esc_url( $video['url'] ); ?>" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                <?php elseif ( ! empty( $image ) ): ?>
                    <img
                        class="w-full h-auto"
                        src="<?php echo esc_url( $image['url'] ); ?>"
                        alt="<?php echo esc_attr( $image['alt'] ); ?>"
                        srcset="<?php echo esc_url( $mobile_image['url'] ); ?> 600w, <?php echo esc_url( $image['url'] ); ?> 1200w"
                        sizes="(max-width: 600px) 600px, 1200px"
                        fetchpriority="high"
                    />
                <?php endif; ?>

                <div class="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-black/60 to-transparent p-6 md:p-12">
                    <?php if ( ! empty( $title ) ): ?>
                        <h1 class="text-white text-3xl md:text-5xl font-bold mb-4">
                            <?php echo esc_html( $title ); ?>
                        </h1>
                    <?php endif; ?>

                    <?php if ( ! empty( $subtitle ) ): ?>
                        <div class="text-white text-lg md:text-xl mb-6">
                            <?php echo wp_kses_post( $subtitle ); ?>
                        </div>
                    <?php endif; ?>

                    <?php if ( ! empty( $cta ) ): ?>
                        <a
                            href="<?php echo esc_url( $cta['url'] ); ?>"
                            class="self-start bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
                        >
                            <?php echo esc_html( $cta['title'] ); ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>