<?php
/**
 * Hero Block Template
 * Generated by Copilot
 */

// Support custom "anchor" values.
$anchor = '';
if ( ! empty($block['anchor']) ) {
    $anchor = esc_attr($block['anchor']);
}

// Create class attribute allowing for custom "className" and "align" values.
$class_name = 'hero-block';
if ( ! empty($block['className']) ) {
    $class_name .= ' ' . esc_attr($block['className']);
}

$slides = get_field('slides'); // Repeater field
?>

<section id="<?php echo $anchor; ?>" class="<?php echo esc_attr($class_name); ?> w-full">
    <div class="relative flex flex-col items-center justify-center">
        <?php if (!empty($slides)) : ?>
          <?php var_dump($slides); ?>
            <div class="carousel w-full">
                <?php foreach ($slides as $slide) :
                    $image = $slide['image'];
                    $mobile_image = $slide['mobile_image'];
                    $video = $slide['video'];
                    $title = $slide['title'];
                    $subtitle = $slide['subtitle'];
                    $cta = $slide['cta'];
                    $carousel_short_title = $slide['carousel_short_title'];
                ?>
                    <div class="carousel-item flex flex-col items-center justify-center w-full">
                        <?php if (!empty($video)) : ?>
                            <video class="w-full h-auto" autoplay muted loop playsinline poster="<?php echo esc_url($image); ?>">
                                <source src="<?php echo esc_url($video); ?>" type="video/mp4">
                            </video>
                        <?php elseif (!empty($image)) : ?>
                            <picture>
                                <?php if (!empty($mobile_image)) : ?>
                                    <source srcset="<?php echo esc_url($mobile_image); ?>" media="(max-width: 768px)">
                                <?php endif; ?>
                                <img src="<?php echo esc_url($image); ?>" alt="<?php echo esc_attr($title); ?>" class="w-full h-auto" fetchpriority="high">
                            </picture>
                        <?php endif; ?>

                        <div class="content-container text-center px-4 py-8">
                            <?php if (!empty($carousel_short_title)) : ?>
                                <p class="text-sm font-medium text-gray-500"><?php echo esc_html($carousel_short_title); ?></p>
                            <?php endif; ?>
                            <?php if (!empty($title)) : ?>
                                <h1 class="text-3xl font-bold text-white"><?php echo esc_html($title); ?></h1>
                            <?php endif; ?>
                            <?php if (!empty($subtitle)) : ?>
                                <div class="mt-2 text-lg text-white"><?php echo wp_kses_post($subtitle); ?></div>
                            <?php endif; ?>
                            <?php if (!empty($cta)) : ?>
                                <a href="<?php echo esc_url($cta['url']); ?>" class="mt-4 inline-block bg-blue-500 text-white px-4 py-2 rounded self-start">
                                    <?php echo esc_html($cta['title']); ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</section>
