<?php

/**
 * Hero Carousel Block Template
 * Generated by Copilot
 */

// Support custom "anchor" values.
$anchor = '';
if (! empty($block['anchor'])) {
    $anchor = esc_attr($block['anchor']);
}

// Create class attribute allowing for custom "className" and "align" values.
$class_name = 'hero-carousel';
if (! empty($block['className'])) {
    $class_name .= ' ' . esc_attr($block['className']);
}

// Get repeater fields.
$slides = get_field('slides'); // Repeater field
if (empty($slides)) {
    return; // Exit if no slides are provided.
}
?>

<section id="<?php echo esc_attr($anchor); ?>" class="<?php echo esc_attr($class_name); ?> w-full">
    <div class="relative flex flex-col items-center justify-center">
        <?php if (count($slides) > 1): ?>
            <div class="carousel w-full">
                <?php foreach ($slides as $slide): ?>
                    <?php
                    $image = $slide['image'];
                    $mobile_image = $slide['mobile_image'];
                    $video = $slide['video'];
                    $title = $slide['title'];
                    $subtitle = $slide['subtitle'];
                    $cta = $slide['cta'];
                    $short_title = $slide['short_title'];
                    ?>
                    <div class="carousel-item flex flex-col items-center justify-center w-full">
                        <?php if (!empty($video)): ?>
                            <video
                                class="w-full h-auto"
                                autoplay
                                loop
                                muted
                                fetchpriority="high">
                                <source src="<?php echo esc_url($video['url']); ?>" type="video/mp4">
                            </video>
                        <?php else: ?>
                            <?php if (!empty($mobile_image)): ?>
                                <img
                                    class="w-full h-auto block lg:hidden"
                                    src="<?php echo esc_url($mobile_image['url']); ?>"
                                    alt="<?php echo esc_attr($mobile_image['alt']); ?>"
                                    fetchpriority="high" />
                            <?php endif; ?>
                            <img
                                class="w-full h-auto <?php echo empty($mobile_image) ? 'block' : 'hidden lg:block'; ?>"
                                src="<?php echo esc_url($image['url']); ?>"
                                alt="<?php echo esc_attr($image['alt']); ?>"
                                fetchpriority="high" />
                        <?php endif; ?>

                        <div class="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-black/60 to-transparent gap-4 p-6 md:p-12">
                            <?php if (!empty($short_title)): ?>
                                <p class="text-sm font-medium text-gray-500"><?php echo esc_html($short_title); ?></p>
                            <?php endif; ?>
                            <?php if (!empty($title)): ?>
                                <h1 class="text-white text-3xl md:text-5xl font-bold"><?php echo esc_html($title); ?></h1>
                            <?php endif; ?>
                            <?php if (!empty($subtitle)): ?>
                                <div class="text-white text-lg md:text-xl"><?php echo wp_kses_post($subtitle); ?></div>
                            <?php endif; ?>
                            <?php if (!empty($cta)): ?>
                                <a
                                    href="<?php echo esc_url($cta['url']); ?>"
                                    class="self-start bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
                                    <?php echo esc_html($cta['title']); ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php else: ?>
            <?php
            $slide = $slides[0];
            $image = $slide['image'];
            $mobile_image = $slide['mobile_image'];
            $video = $slide['video'];
            $title = $slide['title'];
            $subtitle = $slide['subtitle'];
            $cta = $slide['cta'];
            $short_title = $slide['short_title'];

            ?>
            <div class="static-hero w-full">
                <?php if (!empty($video)): ?>
                    <video
                        class="w-full h-auto"
                        autoplay
                        loop
                        muted
                        fetchpriority="high">
                        <source src="<?php echo esc_url($video['url']); ?>" type="video/mp4">
                    </video>
                <?php else: ?>
                    <?php if (!empty($mobile_image)): ?>
                        <img
                            class="w-full h-auto block lg:hidden"
                            src="<?php echo esc_url($mobile_image['url']); ?>"
                            alt="<?php echo esc_attr($mobile_image['alt']); ?>"
                            fetchpriority="high" />
                    <?php endif; ?>
                    <img
                        class="w-full h-auto <?php echo empty($mobile_image) ? 'block' : 'hidden lg:block'; ?>"
                        src="<?php echo esc_url($image['url']); ?>"
                        alt="<?php echo esc_attr($image['alt']); ?>"
                        fetchpriority="high" />
                <?php endif; ?>

                <div class="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-black/60 to-transparent gap-4 p-6 md:p-12">
                    <?php if (!empty($short_title)): ?>
                        <p class="text-sm font-medium text-gray-500"><?php echo esc_html($short_title); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($title)): ?>
                        <h1 class="text-white text-3xl md:text-5xl font-bold"><?php echo esc_html($title); ?></h1>
                    <?php endif; ?>
                    <?php if (!empty($subtitle)): ?>
                        <div class="text-white text-lg md:text-xl"><?php echo wp_kses_post($subtitle); ?></div>
                    <?php endif; ?>
                    <?php if (!empty($cta)): ?>
                        <a
                            href="<?php echo esc_url($cta['url']); ?>"
                            class="self-start bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
                            <?php echo esc_html($cta['title']); ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>